### ISSUE TITLE
Possible monorepo issue: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Extarys** [moh1434/casl-prisma-generator#1]
I have a package for prisma in a monorepo and when I try to execute `casl-generate` I get:

```
monorepo/node_modules/casl-prisma-generator/index.ts:1
import { readFileSync } from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Maybe it doesn't have anything to do with the monorepo and something else is wrong.

Here are the scripts inside packages.json:
```
"generate": "yarn prisma generate && yarn casl-generate",
"casl-generate": "ts-node --transpile-only ./src/casl/generator.ts",
```

I'm not sure why I get this error, my seed file is a typescript file and I currently have no issues with scripts in my prisma package :/
I hope we can get this working, it would save quite some time :) Any clues?

**Comment by moh1434** [comment]
Hmmm, try to import from /dist like this:
`import { generateCaslSubjectsToFile } from 'casl-prisma-generator/dist';`

**Comment by Extarys** [comment]
Oh, thank you! It works :joy: 
I also looked at the source file to set custom path because my prisma schema isn't in the prisma folder 
```
generateCaslSubjectsToFile('src/casl/generated/subjectsList.ts', {}, {
	prismaSchemaPath: __dirname + "/../../schema.prisma"
});
```

Now I get the generated subject list and I'm very excited to learn how to implement CASL :)

**Comment by moh1434** [comment]
> Oh, thank you! It works 😂 I also looked at the source file to set custom path because my prisma schema isn't in the prisma folder
> 
> ```
> generateCaslSubjectsToFile('src/casl/generated/subjectsList.ts', {}, {
> 	prismaSchemaPath: __dirname + "/../../schema.prisma"
> });
> ```
> 
> Now I get the generated subject list and I'm very excited to learn how to implement CASL :)

If you use NestJs, i have a simple example in this [repo](https://github.com/moh1434/nest-prisma-casl-starter)
